version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: "%(levelname)s: %(message)s"
  detailed:
    format: "[%(levelname)-8s|%(module)s|L%(lineno)d] %(asctime)s: %(message)s"
    datefmt: "%Y-%m-%dT%H:%M:%S%z"
  colored:
    (): a4s_eval.utils.logging.ColoredFormatter
    format: "%(asctime)s: [%(colored_levelname)-17s]: %(message)s"
    datefmt: "%Y-%m-%dT%H:%M:%S%z"
handlers:
  stdout:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colored
    stream: ext://sys.stdout
  queue_handler:
    class: logging.handlers.QueueHandler
    handlers:
      - stdout
    respect_handler_level: true
loggers:
  root:
    level: INFO
    handlers:
      - queue_handler
  a4s_eval:
    level: INFO
  uvicorn:
    handlers:
      - queue_handler
  uvicorn.reload:
    handlers:
      - queue_handler
  uvicorn.access:
    level: INFO
    handlers:
      - queue_handler
